### ISSUE TITLE
Is there a way to generate a self-contained HTML file that has the bundle analysis?

### ISSUE THREAD

**Issue by NullVoxPopuli** [simonihmig/ember-cli-bundle-analyzer#298]
for https://limber.glimdown.com, I deploy bundle analysis to bundle.html (currently just the webpack stuff).
For example : https://limber.glimdown.com/bundle.html
(linked to in the header of Limber)

as far as I've been able to tell, this addon _only_(?) relies on middleware triggered by visiting `_analyze`?
Is it worth it to include a flag or something that generates a bundle.html for production? or maybe embroider-only builds are too close to becoming a reality? :thinking: I am not sure

**Comment by simonihmig** [comment]
Sorry for the late answer... I don't think there is much value for this, as the middleware wraps https://github.com/danvk/source-map-explorer, so instead of remove the wrapping middleware part, you could instead just run that lib (it has a standalone bin). Just make sure that you sourcemaps are good and hi-fi (no webpack eval stuff). You could use or copy-paste from https://github.com/simonihmig/ember-cli-bundle-analyzer/blob/master/create-config.js

**Comment by NullVoxPopuli** [comment]
thanks!!
